# Generated by Django 3.1.7 on 2021-03-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platformUsers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="ph_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
