# Generated by Django 3.1.7 on 2021-03-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platformUsers", "0004_auto_20210305_1237"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_type",
            field=models.CharField(
                choices=[("student", "student"), ("teacher", "teacher")], max_length=8
            ),
        ),
    ]
