# Generated by Django 3.1.7 on 2021-03-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformUsers', '0006_auto_20210305_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='profile_pictures'),
        ),
    ]
