# Generated by Django 3.1.7 on 2021-03-08 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pollquestionanswer",
            name="user_choice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.pollquestionchoices",
            ),
        ),
    ]
