# Generated by Django 3.1.7 on 2021-03-08 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_auto_20210308_1252"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollquestionanswer",
            name="choice",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.pollquestionchoices",
            ),
            preserve_default=False,
        ),
    ]
