# Generated by Django 3.1.7 on 2021-03-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_pollquestionanswer_choice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pollquestionanswer",
            name="is_correct",
        ),
    ]
