# Generated by Django 3.1.7 on 2021-03-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_remove_pollquestionanswer_is_correct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="poll_title",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
